remote_theme: pages-themes/cayman@v0.2.0

title: "Sai Rupa Jhade | Data Scientist"
description: "Showcasing data-driven insights, AI projects, and analytics solutions."
plugins:
  - jekyll-remote-theme

# Navigation
navbar-links:
  About: "about.md"
  Projects: "projects.md"
  Resume: "resume.md"
  Contact: "contact.md"

# Social Links
github: Jsairupa
linkedin: sairupajhade
email: sj7740@rit.edu




