remote_theme: pages-themes/minimal@v0.2.0
title: "Sai Rupa Jhade | Data Scientist"
description: "Welcome to my portfolio showcasing data science projects, AI research, and analytics insights."
plugins:
  - jekyll-remote-theme

# Navigation Links (Customize as Needed)
navbar-links:
  About: "about.md"
  Projects: "projects.md"
  Resume: "resume.md"
  Contact: "contact.md"

# Social Links
github: https://github.com/Jsairupa
linkedin: https://www.linkedin.com/in/sairupajhade/
email: sj7740@rit.edu

# Theme Customization (Optional)
show_downloads: true

