remote_theme: pages-themes/slate@v0.2.0
title: "Sai Rupa Jhade | Data Scientist"
description: "Exploring AI, Data Science, and Machine Learning."
plugins:
  - jekyll-remote-theme

# Navigation Links
navbar-links:
  About: "about.md"
  Projects: "projects.md"
  Resume: "resume.md"
  Contact: "contact.md"

# Social Links
github: Jsairupa
linkedin: sairupajhade
email: sj7740@rit.edu




